# Generated by Django 4.1 on 2022-10-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='autor',
            new_name='user',
        ),
    ]
