# Generated by Django 4.1 on 2022-10-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0002_rename_autor_posteo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='puntaje',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
