# Generated by Django 4.1 on 2022-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0004_posteo_imagen_alter_posteo_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteo',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
