# Generated by Django 4.1 on 2022-09-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=50)),
                ('receptor', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
    ]
